### PR TITLE
Add Data Mechanics and Data Mechanics Delight

### PR DESCRIPTION
**Pull request by jystephan**
I'd like to add two tools specific to Apache Spark.
- Data Mechanics is a managed Spark platform, deployed on a Kubernetes cluster inside its customers cloud account (AWS, GCP, and Azure).
   I've put this bullet point under EMR, as we're really in the same category of EMR, but open to feedback.

- Data Mechanics Delight, an open-source monitoring tool for Apache Spark we developed. It works for free on top of any Spark platform (commercial platforms like EMR and Databricks, or even an entirely open-source setup). 

Thanks for providing this awesome list! 
JY - Co-founder of Data Mechanics.

### CODE REVIEW

**Comment by jystephan** [comment]
Hello @igorbarinov, just tagging you to make sure this PR is on your radar, when you get the chance to look at it. Nothing urgent. Thanks!

**Comment by jystephan** [comment]
Happy new year @igorbarinov ! Would love your review when you get the chance. 
https://github.com/datamechanics/delight is an open-source monitoring tool for apache spark!

**Comment by jystephan** [comment]
Hello @igorbarinov, we officially launched Delight: 
https://github.com/datamechanics/delight
https://www.datamechanics.co/blog-post/delight-the-new-improved-spark-ui-spark-history-server-is-now-ga

I'd love if you could take a look at this PR - Thanks 🙏 !

**Comment by vordimous** [comment]
@jystephan, good work and good job keeping up the request.

**Pull request merged**
