### PR TITLE
Add a Community section

### PR DESCRIPTION
**Pull request by davidgasquez**
Hey @igorbarinov! This is the PR adding a community section. I still need to add some blogs and do a small research looking for a Slack or IRC channel where the community gathers.

Closes https://github.com/igorbarinov/awesome-data-engineering/issues/39

### CODE REVIEW

**Comment by davidgasquez** [comment]
I think we could merge this and keep updating it as we go!

**Comment by davidgasquez** [comment]
Any updates on this?

**Comment by davidgasquez** [comment]
Sorry! Just removed it 😄

**Comment by davidgasquez** [comment]
Can we move forward now? 😄

**Comment by igorbarinov** [comment]
TY

**Pull request merged**
